version: "3"

services:
  app:
    image: dockerimage
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
    restart: always
    volumes:
      - dbconfig:/data/configdb
      - dbdata:/data/db

volumes:
  dbconfig:
  dbdata:

