version: "3"

services:
  app:
    build: 'dockerimage'
    environment:
      MONGO_URL: "mongodb://db:27017/${COMPOSE_DBNAME}"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"
    volumes:
      - ".:/usr/src"
      # - "/usr/src/node_modules"

  db:
    image: mongo
    restart: always
    volumes:
      - dbconfig:/data/configdb
      - dbdata:/data/db

volumes:
  dbconfig:
  dbdata:

